
friend void CloseMHandler(System::Classes::TBytesStream* Mem_Space, const String Dest_Path, bool AppendFile);
friend System::Classes::TBytesStream* Create_Meter_Space(String Init_Str);
friend void ReadMHandler(System::Classes::TBytesStream* Mem_Space, pDoubleArray2d X_axis, pStringArray1d Ylabels, pDoubleArray2d Y_axis);
friend void Write_String(System::Classes::TBytesStream* Mem_Space, const String Content);
friend void WriteintoMem(System::Classes::TBytesStream* Mem_Space, double Content);
friend void WriteintoMemStr(System::Classes::TBytesStream* Mem_Space, String Content);




